global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'jupyter'
    static_configs:
      - targets: ['jupyter:8888']

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
