name: Code Checks

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Python code
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      run: |
        pip install black flake8
        black --check .
        flake8 .
    
    - name: Check JavaScript code
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      run: |
        npm install
        npm run lint
